# Generated by Django 5.1.1 on 2025-01-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='models3d/images/'),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='file',
            field=models.FileField(upload_to='models3d/files/'),
        ),
    ]
