# Generated by Django 5.1.1 on 2025-03-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='models3d/files/'),
        ),
        migrations.AddField(
            model_name='model3d',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='models3d/images/'),
        ),
    ]
