# Generated by Django 5.1.1 on 2025-02-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_model3d_image_alter_model3d_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
