# Generated by Django 5.1.1 on 2025-03-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_model3d_file_model3d_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model3d',
            name='file',
        ),
        migrations.RemoveField(
            model_name='model3d',
            name='image',
        ),
    ]
