# Generated by Django 5.1.1 on 2025-03-31 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='volume',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
