# Generated by Django 5.1.1 on 2025-04-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_recyclinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
