# Generated by Django 5.1.1 on 2025-04-24 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='material',
            field=models.CharField(default='PET', max_length=50, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Tipo/Marca'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='volume',
            field=models.CharField(max_length=20, verbose_name='Volume'),
        ),
    ]
