# Generated by Django 5.1.1 on 2025-04-29 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_bottle_material_alter_bottle_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottle',
            name='material',
        ),
        migrations.AlterField(
            model_name='bottle',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='volume',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
