# Generated by Django 5.1.1 on 2025-04-30 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_marketplacesettings_marketplacetransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reputation_amount', models.IntegerField()),
                ('recycling_amount', models.IntegerField()),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('acceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_history_as_acceptor', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_history_as_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reputation_coins_offered', models.IntegerField()),
                ('recycling_coins_wanted', models.IntegerField()),
                ('exchange_rate', models.FloatField()),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_offers', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModelPrintCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recycling_coins', models.IntegerField(default=10)),
                ('estimated_filament', models.IntegerField(default=50)),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='print_cost', to='api.model3d')),
            ],
        ),
        migrations.DeleteModel(
            name='MarketplaceSettings',
        ),
        migrations.AddField(
            model_name='exchangehistory',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.exchangeoffer'),
        ),
        migrations.DeleteModel(
            name='MarketplaceTransaction',
        ),
    ]
