# Generated by Django 5.1.1 on 2025-05-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_exchangehistory_exchangeoffer_modelprintcost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeoffer',
            name='accepted_by',
        ),
        migrations.RemoveField(
            model_name='exchangeoffer',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='modelprintcost',
            name='model',
        ),
        migrations.AddField(
            model_name='model3d',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='model3d',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ExchangeHistory',
        ),
        migrations.DeleteModel(
            name='ExchangeOffer',
        ),
        migrations.DeleteModel(
            name='ModelPrintCost',
        ),
    ]
